### ISSUE TITLE
kali can not run it 

### ISSUE THREAD

**Issue by wiwei132** [postrequest/link#5] opened 2021-06-30 03:13 UTC
when finished all install 
./link run it   
it feedfack erros like：
im not use root to install it 

 Please provide bind address (eg: 0.0.0.0:443): 
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorStack([Error { code: 33558530, library: "system library", function: "fopen", reason: "No such file or directory", file: "../crypto/bio/bss_file.c", line: 288, data: "fopen('cert/key.pem','r')" }, Error { code: 537346050, library: "BIO routines", function: "file_ctrl", reason: "system lib", file: "../crypto/bio/bss_file.c", line: 290 }, Error { code: 336265218, library: "SSL routines", function: "SSL_CTX_use_PrivateKey_file", reason: "system lib", file: "../ssl/ssl_rsa.c", line: 521 }])', src/server/spawn.rs:34:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

i can't find any information from google！  

thanks for your response?^_^ Have a nice day !

**Comment by fyfztms** [comment] 2021-06-30 08:31
me too

**Comment by Ocean-Y** [comment] 2021-07-01 12:19
me too

**Comment by postrequest** [comment] 2021-07-01 13:42
This is a duplicate of [#2](https://github.com/postrequest/link/issues/2).

I have updated link with [this](https://github.com/postrequest/link/commit/e2170c6e928b6d0c064392878df572230d189e21) commit, and you should now be prompted for the folder with your certificates.

**Closed by postrequest** 2021-07-01 13:42 UTC
Labels: bug, duplicate
